# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cd6620c3840c3be5865d79998f3092d5b17ba606d847d82e856c80534331a5aa3ced02468a11c3b8e5376379c7bbdcc96460793d97f32939ca92b9783532a58b

test:
  secret_key_base: 5ebc84c98589dca311b25f66c0eb30e7b75bbd9b671064b364843355816ea7beb9f36cafb28aaf5ba05aadbd725aa604ddf63105d029a1be239273a2dcca884e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
